// Maps our team ids (FIFA-style 3-letter codes from football-data.org's
// "tla" field) to flagcdn.com codes. England/Scotland use flagcdn's UK
// subdivision codes (gb-eng/gb-sct) since they have no ISO 3166-1 code.
const FLAG_CODES: Record<string, string> = {
	ALG: "dz",
	ARG: "ar",
	AUS: "au",
	AUT: "at",
	BEL: "be",
	BIH: "ba",
	BRA: "br",
	CAN: "ca",
	CIV: "ci",
	COD: "cd",
	COL: "co",
	CPV: "cv",
	CRO: "hr",
	CUW: "cw",
	CZE: "cz",
	ECU: "ec",
	EGY: "eg",
	ENG: "gb-eng",
	ESP: "es",
	FRA: "fr",
	GER: "de",
	GHA: "gh",
	HAI: "ht",
	IRN: "ir",
	IRQ: "iq",
	JOR: "jo",
	JPN: "jp",
	KOR: "kr",
	KSA: "sa",
	MAR: "ma",
	MEX: "mx",
	NED: "nl",
	NOR: "no",
	NZL: "nz",
	PAN: "pa",
	PAR: "py",
	POR: "pt",
	QAT: "qa",
	RSA: "za",
	SCO: "gb-sct",
	SEN: "sn",
	SUI: "ch",
	SWE: "se",
	TUN: "tn",
	TUR: "tr",
	URU: "uy",
	USA: "us",
	UZB: "uz",
};

export function getFlagUrl(teamId: string, width = 40): string | null {
	const code = FLAG_CODES[teamId];
	return code ? `https://flagcdn.com/w${width}/${code}.png` : null;
}
